AWSTemplateFormatVersion: '2010-09-09'
Description: IAM resources for apisq (https://github.com/apisq/bootstrap)

Resources:

  CloudformationDeployStacksRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-cloudformation-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      Policies:
        - PolicyName: cloudformation-deploy-stacks
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:Describe*
                  - cloudformation:Get*
                  - cloudformation:List*
                Resource: "*"
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  Fn::GetAtt: [ CloudformationDeployResourcesRole, Arn ]

  CloudformationDeployResourcesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-resources-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - Ref: CloudformationDeployResourcesPolicy1

  CloudformationDeployResourcesPolicy1:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-resources-policy-1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Allow all Lambda actions
          - Effect: Allow
            Action: lambda:*
            Resource:
              Fn::Sub: arn:aws:lambda:*:${AWS::AccountId}:function:apisq-*
          # Except Lambda invoke
          - Effect: Deny
            Action: lambda:Invoke*
            Resource: '*'
          # Allow all DynamoDB actions
          - Effect: Allow
            Action: dynamodb:*
            Resource:
              - Fn::Sub: arn:aws:dynamodb:*:${AWS::AccountId}:table:apisq-*
              - Fn::Sub: arn:aws:dynamodb:*:${AWS::AccountId}:global-table:apisq-*
          # Except DynamoDB items
          - Effect: Deny
            Action:
              - dynamodb:*Item*
              - dynamodb:Query
              - dynamodb:Scan
            Resource: '*'

Outputs:
  DeployCloudformationRoleArn:
    Value:
      Fn::GetAtt: [ CloudformationDeployStacksRole, Arn ]
  DeployResourcesRoleArn:
    Value:
      Fn::GetAtt: [ CloudformationDeployResourcesRole, Arn ]
